from languages.models import Language

language_codes = {
    'af': 'Afrikaans',
    'am': 'Amharic',
    'ar': 'Arabic',
    'as': 'Assamese',
    'az': 'Azerbaijani',
    'ba': 'Bashkir',
    'bg': 'Bulgarian',
    'bho': 'Bhojpuri',
    'bn': 'Bengali',
    'bo': 'Tibetan',
    'brx': 'Bodo',
    'bs': 'Bosnian',
    'ca': 'Catalan',
    'cs': 'Czech',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'doi': 'Dogri',
    'dsb': 'Lower Sorbian',
    'dv': 'Divehi',
    'el': 'Greek',
    'en': 'English',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fil': 'Filipino',
    'fj': 'Fijian',
    'fo': 'Faroese',
    'fr': 'French',
    'fr-CA': 'Canadian French',
    'ga': 'Irish',
    'gl': 'Galician',
    'gom': 'Goan Konkani',
    'gu': 'Gujarati',
    'ha': 'Hausa',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hne': 'Chhattisgarhi',
    'hr': 'Croatian',
    'hsb': 'Upper Sorbian',
    'ht': 'Haitian Creole',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'id': 'Indonesian',
    'ig': 'Igbo',
    'ikt': 'Inuinnaqtun',
    'is': 'Icelandic',
    'it': 'Italian',
    'iu': 'Inuktitut',
    'iu-Latn': 'Inuktitut (Latin)',
    'ja': 'Japanese',
    'ka': 'Georgian',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'kmr': 'Kurmanji',
    'kn': 'Kannada',
    'ko': 'Korean',
    'ks': 'Kashmiri',
    'ku': 'Kurdish',
    'ky': 'Kyrgyz',
    'ln': 'Lingala',
    'lo': 'Lao',
    'lt': 'Lithuanian',
    'lug': 'Ganda',
    'lv': 'Latvian',
    'lzh': 'Literary Chinese',
    'mai': 'Maithili',
    'mg': 'Malagasy',
    'mi': 'Maori',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn-Cyrl': 'Mongolian (Cyrillic)',
    'mn-Mong': 'Mongolian (Mongolian Script)',
    'mr': 'Marathi',
    'ms': 'Malay',
    'mt': 'Maltese',
    'mww': 'Hmong Daw',
    'my': 'Burmese',
    'nb': 'Norwegian Bokmål',
    'ne': 'Nepali',
    'nl': 'Dutch',
    'nso': 'Northern Sotho',
    'nya': 'Chichewa',
    'or': 'Odia',
    'otq': 'Querétaro Otomi',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'prs': 'Dari',
    'ps': 'Pashto',
    'pt': 'Portuguese',
    'pt-PT': 'European Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'run': 'Rundi',
    'rw': 'Kinyarwanda',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sm': 'Samoan',
    'sn': 'Shona',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr-Cyrl': 'Serbian (Cyrillic)',
    'sr-Latn': 'Serbian (Latin)',
    'st': 'Southern Sotho',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'ti': 'Tigrinya',
    'tk': 'Turkmen',
    'tlh-Latn': 'Klingon (Latin)',
    'tn': 'Tswana',
    'to': 'Tongan',
    'tr': 'Turkish',
    'tt': 'Tatar',
    'ty': 'Tahitian',
    'ug': 'Uyghur',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    'vi': 'Vietnamese',
    'xh': 'Xhosa',
    'yo': 'Yoruba',
    'yua': 'Yucatec Maya',
    'yue': 'Cantonese',
    'zh-Hans': 'Chinese (Simplified)',
    'zh-Hant': 'Chinese (Traditional)',
    'zu': 'Zulu'
}

# to run run the function
def run():
    for code, language in language_codes.items():
        new_language = Language(title=language, code=code)
        new_language.save()
        print(f"loaded--{language}-{code}")


if __name__ == '__main__':
    run()
